# Generated by Django 2.1.7 on 2019-03-01 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movielistapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='awards',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='dvd',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='note',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='scenarist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenarist', to='movielistapp.Person'),
        ),
    ]
