# Generated by Django 2.1.7 on 2019-03-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielistapp', '0002_auto_20190301_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='released',
            field=models.DateField(),
        ),
    ]
