# Generated by Django 2.1.7 on 2019-03-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielistapp', '0003_auto_20190303_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdbID',
            field=models.CharField(default='tt3896198', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
