# Generated by Django 2.1.7 on 2019-03-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielistapp', '0005_auto_20190311_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='scenarist',
        ),
        migrations.AddField(
            model_name='movie',
            name='scenarist',
            field=models.ManyToManyField(related_name='scenarist', to='movielistapp.Person'),
        ),
    ]
