# Generated by Django 2.1.7 on 2019-03-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielistapp', '0006_auto_20190311_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='scenarist',
            field=models.ManyToManyField(related_name='scenarists', to='movielistapp.Person'),
        ),
    ]
