# Generated by Django 2.1.7 on 2019-03-13 09:37

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('movielistapp', '0007_auto_20190311_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='note',
        ),
        migrations.AddField(
            model_name='movie',
            name='ratings',
            field=django_mysql.models.JSONField(default=dict),
        ),
    ]
