# Generated by Django 2.1.7 on 2019-03-13 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movielistapp', '0005_auto_20190306_1123'),
        ('movielistapp', '0008_auto_20190313_1037'),
    ]

    operations = [
    ]
