# Generated by Django 2.1.7 on 2019-03-23 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movielistapp', '0014_extension_20190323_1654'),
        ('movielistapp', '0013_auto_20190323_1145'),
    ]

    operations = [
    ]
