# Generated by Django 2.1.7 on 2019-03-25 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movielistapp', '0013_auto_20190323_1145'),
        ('movielistapp', '0014_extension_20190323_1654'),
    ]

    operations = [
    ]
