# Generated by Django 2.1.7 on 2019-03-27 10:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movielistapp', '0015_merge_20190325_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listmovie',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movielistapp.State'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='plot',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='ratings',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
